### PR TITLE
Phase out AE2 Inscribers

### PR DESCRIPTION
**Pull request by NotMyWing**
Phases out AE2 Inscribers and AE2Stuff Inscribers in favor of GregTech Forming Presses and Circuit Assemblers. This accounts for Quantum/Magnet Cards as well. The quests are adjusted appropriately.

The Printed Circuits require MV Forming Presses with their respective AE2 Inscriber Presses, and to finish the circuit, a Circuit Assembler is required (using Tin/Soldering Alloy following the standard recipes). The standard GT Forming Presses have recipes that are pretty much identical to these of the AE2 Inscribers.

This greatly enhances the overall AE2 experience in late game, making the player not depend on ridiculously slow Inscribers/spamming them when making high-tier Storage Cells and large Crafting CPUs en masse. Additionally, GCYM machines can be used later on with distinct buses to greatly enhance the crafting speed of Printed Circuits.

The old Inscriber recipes are kept intact to avoid breaking worlds, however the machines themselves are no longer craftable, so it's encouraged to switch over.

image

### CODE REVIEW

**Comment by IntegerLimit** [comment]
I really like how this gives a good use to forming presses, especially relating to GCYM multi ones.

**Comment by tracer4b** [comment]
Mirroring what I said in the discord: I acknowledge the difficulty in crafting AE2 processors late game, but I also don't want to fully phase out the AE2 inscriber. Not everything should be in a GT machine.  

I'm thinking about adding a recipe for the AE2 processors which can only be done in a multiblock. That would allow the inscriber to exist while still solving them being slow late game

**Comment by IntegerLimit** [comment]
> Mirroring what I said in the discord: I acknowledge the difficulty in crafting AE2 processors late game, but I also don't want to fully phase out the AE2 inscriber. Not everything should be in a GT machine.
> 
> I'm thinking about adding a recipe for the AE2 processors which can only be done in a multiblock. That would allow the inscriber to exist while still solving them being slow late game

Yeah, that sounds good. Maybe, with the coremod, we can make it be in a Large Forming Press, perhaps with research too.

@tracer4b should we close this for now?

**Comment by IntegerLimit** [comment]
Closing for now, to be implemented in some way via coremod (most likely endgame multi).

**Pull request closed without merging**
