### PR TITLE
Reinstate that PAuto Packagers can be Placed Anywhere

### PR DESCRIPTION
**Pull request by Doniazade**
Adds one sentence to the pauto quest, see image. I haven't figured out the BQ scripts yet so you'll have to sync this to the other books manually as needed.

image

Tested on 1.7.6 nightly

(This information already exists in the extended crafting quest, but should be in the main pauto quest.)

### CODE REVIEW

**Comment by IntegerLimit** [comment]
It would be greatly appreciated if the next PRs that you make be based from a branch that is not your 'main' branch.

**Comment by IntegerLimit** [comment]
No need to sync to other quest books, I'll do that once this PR is done.

One change I would like you to make:
Can you change the 'Automating Extended Crafting' Quest so that, instead of saying 'place a Packager next to your Unpackager' it says 'place a Packager anywhere on your AE Network'?

Thanks in advance!

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
See Above.

**Comment by IntegerLimit** [comment]
Another change: The text should not be green, as this is not a feature specific to Nomi-CEu.

**Comment by Doniazade** [comment]
Will try to get these changes in tonight CET. Still learning github workflow.

Was unsure about the color scheme and what was notable positive vs ceu change.

**Review by IntegerLimit — APPROVED** [review]

**Pull request merged**
