### PR TITLE
GT 2.8 questbook update 

### PR DESCRIPTION
**Pull request by tracer4b**
This PR contains updates to the QB for 1.7-a2, especially for changes made in CEu 2.8

- [x] Address https://github.com/GregTechCEu/GregTech/pull/2195
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2184
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2137
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2139
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2185 and related balancing
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2163
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2077
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2128
- [x] Address https://github.com/GregTechCEu/GregTech/pull/2164
- [x] Make a new ore finding quest for inclusion of visual ores
- [x] Fix the other QB issues reported
- [x] HV Energy Hatch Quest needs Cleanroom

### CODE REVIEW

**Comment by serenibyss** [comment]
Suggestions:
- [ ] Add a quest explaining multiblock rotation that was added in 2.8. Allowed by all multis except: PBF, coke oven, primitive pump, cleanroom, charcoal pile igniter, multiblock miners/fluid rigs, distillation tower, and GCYM fractioning distillery
- [ ] Add a quest (or add a quest description somewhere) for https://github.com/GregTechCEu/GregTech/pull/2139

**Comment by IntegerLimit** [comment]
- [ ] Reflect changes in https://github.com/Nomi-CEu/Nomi-Labs/pull/5
- [ ] Reflect Snad Change (if needed)

**Comment by IntegerLimit** [comment]
Current GT 2.8 Note Changes:
- Tungsten Steel Coil -> RTM Alloy Coil

**Review by a-a-GiTHuB-a-a — CHANGES_REQUESTED** [review]
shouldn't it say _your_ system in the titanium quest, not _you're_ system?

**Comment by IntegerLimit** [comment]
Do not close the issues when you fix them. Instead, edit the original title to include the issue you fixed, in the format:
`Fixes #<issue_num>`

**Comment by IntegerLimit** [comment]
- [ ] Add a quest or mention (like in lens quest) for Chemical Dyes, noting they can be infinitely looped

**Comment by IntegerLimit** [comment]
New Issue:
- [ ] https://github.com/Nomi-CEu/Nomi-CEu/issues/667

**Comment by IntegerLimit** [comment]
Another new issue:
- [ ] https://github.com/Nomi-CEu/Nomi-CEu/issues/672

This might need to be applied to other similar quests.

**Pull request closed without merging**
