### PR TITLE
Add Uber Conduit Probe

### PR DESCRIPTION
**Pull request by D-Alessian**
see https://github.com/Nomi-CEu/Nomi-CEu/issues/1098

made the PR to save the 5 minutes it takes to fetch the IDs from CurseForge in case you do want to add it.

### CODE REVIEW

**Comment by IntegerLimit** [comment]
A quest must also be added for this. Perhaps it could be mentioned in an existing conduit probe quest, if it exists, or a new quest would have to be added.

**Comment by D-Alessian** [comment]
> A quest must also be added for this. Perhaps it could be mentioned in an existing conduit probe quest, if it exists, or a new quest would have to be added.

I'll get on that.

**Comment by IntegerLimit** [comment]
The quests can be done in a seperate PR. I'll merge this.

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
Please place the new mod in order (note, the file is sorted by `projectID`).

**Comment by D-Alessian** [comment]
sorry I forgot I had this open, I had the QB nearly ready for a while too

**Review by IntegerLimit — APPROVED** [review]

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
Please port the QB changes to Hard Mode. Make sure to load the qb and add the new quest to the relevant questline, after porting with the tool.

**Review by IntegerLimit — APPROVED** [review]

**Comment by IntegerLimit** [comment]
Please run `npm run gulp fixQB`, that should fix the status check error.

**Pull request merged**
