### PR TITLE
Groovy: Add mod recipe changes back

### PR DESCRIPTION
**Pull request by LetterN**
title.

## Mods
- [x] AE2
- [x] AdvRocketry
- [x] SolarFlux

## Meta
- [x] OreDictionary
- [x] GT Materials

## Issues
thermal expansion tanks on advanced rocketry not resolved
advrocketry extreme crafting not implemented

### CODE REVIEW

**Comment by IntegerLimit** [comment]
Thank you for helping the effort to transfer the pack over to groovy. What is the 'mod configs' specified here? Is it just custom configs and recipes?

**Comment by brachy84** [comment]
Wdym there is no `metaitem` resolver? Just do `metaitem('whatever')`. 🤔

**Comment by IntegerLimit** [comment]
Please do not do pack-mode related stuff until later. I recommend referring to the CT-> GS PR for the order that it should be done in.

**Comment by IntegerLimit** [comment]
The recipes are starting to look good. I'll keep working on other stuff (like hand framing tool, custom multis, wrenchable creative blocks, etc.).

**Comment by IntegerLimit** [comment]
Because this is a pr to a development branch, I'll simply merge this, and make any changes later.

**Pull request merged**
