### PR TITLE
Move Genesis quests, eliminate overlapping lines

### PR DESCRIPTION
**Pull request by sparr**
The vertical prerequisite lines between Electronics Subcomponents, Primitive Steelworks, and Your First Circuit overlap in an ambiguous way. This change moves two of them to avoid that.
image

This problem does not exist in the expert quest book.

### CODE REVIEW

**Review by IntegerLimit — COMMENTED** [review]
Can you include a screenshot of what it looks like now? Otherwise, looks good.

**Comment by sparr** [comment]
Current qb layout with the overlapping lines
image

**Comment by IntegerLimit** [comment]
> Current qb layout with the overlapping lines image

This is the current layout, correct?

**Comment by sparr** [comment]
Yes

**Comment by IntegerLimit** [comment]
Sorry, but I think the new version looks too messy. The old version is fine, as the quests, while not dependent on each other, are still related. If you have further suggestions/ideas, comment on this PR, or make a new one.

**Pull request closed without merging**
