### PR TITLE
Update to GT 2.8.* & Integrate Nomi Labs (#542)

### PR DESCRIPTION
**Pull request by IntegerLimit**
# PR to Update GregTech CEu to v2.8.*, and to integrate Nomi Labs (our coremod)

## Problems Solved
- Fixes Multi Searching in JEI (https://github.com/Nomi-CEu/Nomi-CEu/issues/519)
- Fixes Vanilla Ores in JEI (https://github.com/Nomi-CEu/Nomi-CEu/issues/271)
- Fixes Rhodium Plated Palladium not being renamed Correctly
- Addresses Buckets showing up in JEI (https://github.com/Nomi-CEu/Nomi-CEu/issues/602)
- Specifies Default Fluids for All Fluid Conflicts (https://github.com/Nomi-CEu/Nomi-CEu/issues/602)
- Removes Bogo Feature in Bogo Sort
- Fixes Oxygen, Hydrogen and Nitrogen showing up as a null texture in JEI/HEI
- Fixed IV Quad/Nonuple Hatches & Buses being uncraftable (https://github.com/Nomi-CEu/Nomi-CEu/issues/550)
- Fixes the language override for Rhodium Plated Lumium-Palladium
- Fixes NBT Recipe Problems (https://github.com/Nomi-CEu/Nomi-CEu/issues/541, https://github.com/Nomi-CEu/Nomi-CEu/issues/518, https://github.com/Nomi-CEu/Nomi-CEu/issues/435, ...)
- Fixes Naq Line Problems in Hard Mode (https://github.com/Nomi-CEu/Nomi-CEu/issues/525)
- Fixes HM Assembly Line Recipe Duplicate (https://github.com/Nomi-CEu/Nomi-CEu/issues/517)
- Fixes Some HM Assembly Line Recipes not having Research
- Fixes Recycling Recipes (https://github.com/Nomi-CEu/Nomi-CEu/issues/517, ...)

## New Features
- Removes Anvil XP Scaling
- Custom Items, Blocks, and Multis Improvements
- EnderIO Capacitor and Custom Capacitor Improvements
- Draconic Energy Storage Core Improvements
- Remapping and Removal of old and deprecated items (such as Content Tweaker Blaze Powder + Dark Red Coal)
- Red Coal NBT Removal (along with all of xu2's frequency)!
- Allows Ignoring some Missing Registries
- Genesis now is slowly revealed

## Balancing Changes
- Added Cobaltite to the T3 Micro Miner

## Internal Changes
- TON of new Groovy Helpers!

## Issues Closed
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/519
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/441
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/541
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/550
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/480
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/518
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/525
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/510
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/517
Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/435

## PRs Superseeded
Superseeds https://github.com/Nomi-CEu/Nomi-CEu/pull/537

## Issues Addressed (Partially Fixed)
Addresses https://github.com/Nomi-CEu/Nomi-CEu/issues/271 (GT Ores Left)
Addresses https://github.com/Nomi-CEu/Nomi-CEu/issues/602 (Misc Cleanup & Dealing with https://github.com/Nomi-CEu/Nomi-CEu/issues/370 Left)

### Mod Changes So Far:
- Added Nomi-Labs 0.6.0
- Removed Content Tweaker
- Removed DevTech
- Removed Multiblock Tweaker
- Updated GroovyScript to 0.7.3
- Updated GregTech to 2.8.6
- Updated GCYM to 1.2.7
- Updated ULV Covers to 2.8.0
- Updated ModularUI to 2.4.2
- Updated BogoSort to 1.4.6
- Added VisualOres 0.2.4

### Roadmap / TODO:
- [x] Remove Multiblock Registries
- [x] Check if lines 1327, 1330, 1342, and 1344 in `_oreDict.zs` are needed
- [x] Fix CT Errors (Apart from Conflicting Recycling Recipes)
- [x] Fix GS Errors
- [x] Fix Original Recycling Replacements (lines starting with `//<recipemap:arc_furnace>.findRecipe`). Maybe use groovy helpers to do so?
- [ ] Fix ABS Removals (lines starting with `//<recipemap:alloy_blast_smelter>.findRecipe`). Use groovy helpers to do so.
- [x] Fix Quest Book Items (Remapping stuff)
- [ ] Final Check Quest Book Items with Regex (Remapping stuff)
- [ ] Fix Quest Book Multiblocks (Meta ID Changed)
- [ ] Softcode Tooltips
- [ ] Clean up code (use the new groovy helpers)
- [ ] Check compat between moving versions (remapppers, stuff like that. Also materials, drac energy core)
- [ ] Check for more Recycling Replacements
- [ ] Check if works on server
- [ ] Fix Dupe HM UV Field Gen Assembly Line Recipe (Fixes https://github.com/Nomi-CEu/Nomi-CEu/issues/510)
- [ ] Changes relevant to Tungstensteel Coil -> RTM Alloy Coil
- [ ] Fix Most HM Assembly Line Recipes not having research (Stab mms, universal crystalizer, tier 3 ore/fluid miner?)
- [ ] Fix NBT Recipes (https://github.com/Nomi-CEu/Nomi-CEu/issues/518, https://github.com/Nomi-CEu/Nomi-CEu/issues/435, ...)
  - Quarktech recipe needing laptronic orb with specific nbt? Terracotta recipe? Check all recipes with Laptronic Orb or Batteries as ingredients. Check recipes with capacitors and/or jetpacks as ingredients.
- [ ] Fix Naq Line Problems in Hard Mode (https://github.com/Nomi-CEu/Nomi-CEu/issues/525)
- [ ] Fix Recycling Recipes (https://github.com/Nomi-CEu/Nomi-CEu/issues/517, ...)
- [ ] Fix https://github.com/Nomi-CEu/Nomi-CEu/issues/480 (Temporarily, to allow for smooth transition).
- [ ] Perhaps discuss issues in https://github.com/Nomi-CEu/Nomi-CEu/issues/472?

### CODE REVIEW

**Comment by serenibyss** [comment]
Should update to GT 2.8.4

**Comment by IntegerLimit** [comment]
2.8.5 actually

**Comment by serenibyss** [comment]
When you update to 2.8.5, in `_oreDict.zs` remove the two lines at 1381 and 1384 for registering GT blocks for chisel. They are handled by GT now in this version

**Comment by IntegerLimit** [comment]
> When you update to 2.8.5, in `_oreDict.zs` remove the two lines at 1381 and 1384 for registering GT blocks for chisel. They are handled by GT now in this version
> 
> Also the lines at 1330 and 1344 for Coal Coke Block oredict, also handled by GT now

Ok, thanks.

**Comment by IntegerLimit** [comment]
As with the latest commit, the game now launches.

**Pull request closed without merging**
