### PR TITLE
Add Nomicoin-Free Airtight Seal Recipes

### LINKED ISSUE #941: Airtight Seal enchant book recipe for HM
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

Applies to every version

### Environment

Applies to every environment

### Mode

Expert Mode

### Related Problem

Airtight Seal is currently unavailable in HM because it's normally crafted with Nomidollars.

### Your Solution

I propose simply adding any kind of recipe to make it obtainable in HM, since it's a major quality of life increase for players who build in space.

### How Will Your Solution Work

Add any accessible recipe, for example drill cores got a gregified recipe. I think the recipe should be craftable around late HV or mid EV with some effort, since that's about when space becomes relevant.

### Alternatives You've Considered

There is no alternative currently in the game except for cheating or using space suits the whole game if you're building in space in HM.

### Additional Information

This feature requests relatates to my recent quest fix PR which includes Airtight Seal in the suit + suit workstation quests.

### PR DESCRIPTION
**Pull request by v3ect0rgames**
Adds airtight recipes to NM and HM, in NM allows you to craft without nomicoins.

Fixes #941

### CODE REVIEW

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
Move recipes to `midgame.groovy` or a new file called `advancedRocketry.groovy` (in Mod-Specific)

Move HM recipe to GrS, following the [GrS Docs for Extended Crafting](https://cleanroommc.com/groovy-script/mods/extendedcrafting/table_crafting).

**Comment by v3ect0rgames** [comment]
Fixed Requested Changes

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
Use MetaItems and OreDict handlers instead of unreadable GT Item Specifications.

**Review by IntegerLimit — APPROVED** [review]

**Comment by IntegerLimit** [comment]
Final Recipes:

NM:
image

HM:
image

**Pull request merged**
