### PR TITLE
Mod Updates As Specified In #472

### PR DESCRIPTION
**Pull request by HandsomeAsianMan**
## Whats done   
1. Betterer P2P  
2. AE2 UEL update  
3. Changed ae2stuff to ae2stuff unofficial   
    1. Encoder was removed which affected the recipe for packaged auto encoder
    2. For now i have just replaced it with hv hull so the script works
4. Updated Nae2   
    1. Haven't added recipes for the anything yet  
5. Updated Alfheim  
6. Updated universal tweaks  
7. Updated vintage fix  
8. Updated loliasm  

## Needs done
1. AE2 stuff encoder replacement
2. Recipes for extra stuff added by nae2

### CODE REVIEW

**Comment by IntegerLimit** [comment]
Please update Had Enough Items as well, otherwise Alfheim kills memory.

Furthermore, can you please undo the update to Universal Tweaks?
There are some config options that I would like to try out.

For AE2 Stuff Encoder, there might need to be more done.

There also needs to be a JEI description page for AE2 Sticky Cards, and Quests for NAE2 (Although that can be in a seperate PR)

**Comment by HandsomeAsianMan** [comment]
[Updated mods from nomi 1.7.4.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/14872194/Updated.mods.from.nomi.1.7.4.txt)
found some other mods to consider updating aswell

**Comment by HandsomeAsianMan** [comment]
FluidCells
nae2Cells

**Comment by HandsomeAsianMan** [comment]
For the sticky card. Idk what to actually do by making a jei page for it but here is the description.  

Sticky Card is used to define exclusive destinations for items/fluids storage making it so all items inputted into the system will be stored there regardless of priority. If the designated storage is full, the designated item will NOT go anywhere else even if space is available elsewhere.

**Comment by IntegerLimit** [comment]
I will make the JEI desc, leave that to me in a future PR (which will include NAE2 quests)

**Comment by HandsomeAsianMan** [comment]
Aight cool this is basically done than if ur happy with the cell recipes n stuff

**Comment by IntegerLimit** [comment]
I am also concerned about the removal of the ae2 stuff pattern encoder. What will happen to existing items in pattern encoders? Can Pattern Encoders store items? What would be the closest full block that is equal to it?

**Comment by HandsomeAsianMan** [comment]
The only item that u c store in are patterns I think. Up to a stack, the recipe slots are filled with fake items. So maybe some people will lose those if they have an encoder placed around. They also count as an ae2 network part and some people might have one placed around just to connect up their ae2 system instead of a cable or other block. That's about it. So the closest full block is probably just a full block interface?

**Comment by IntegerLimit** [comment]
As requested, I will perform some formatting changes on this PR.

**Review by IntegerLimit — APPROVED** [review]

**Comment by IntegerLimit** [comment]
Balancing Changes:
256k cells are now iv, and are assembler recipes
image

Changes in EUt for 4096k and 16384k
image
image

**Review by tracer4b — APPROVED** [review]

**Pull request merged**
