### PR TITLE
Fix Mac/Linux Pack Mode Switcher Erroring

### PR DESCRIPTION
**Pull request by uku3lig**
if `server.properties` is not present in the minecraft directory, it will try to delete it which will fail and exit the script due to `set -e`

### CODE REVIEW

**Review by IntegerLimit — APPROVED** [review]
Approved, but waiting for the person who wrote those lines to quickly look over it.

**Comment by 0xC4DE** [comment]
Small nitpick -- the rm was just to insure it's gone, you can eat error codes with `|| true`, Alternatively, removing `set -e` could have been a better option. 

This works, too. Thought I started with `cp`, hence the `rm` after the copy, but it got changed to `mv` at some point.

**Comment by IntegerLimit** [comment]
@uku3lig are you going to implement the suggestions above?

**Comment by uku3lig** [comment]
my bad, i misunderstood what 0xC4DE meant. i added what was suggested

**Comment by IntegerLimit** [comment]
> my bad, i misunderstood what 0xC4DE meant. i added what was suggested

Sorry if I'm misunderstanding, but:
Your previous commit was an error
Where is the fix?

**Comment by uku3lig** [comment]
1091b039090124f3ee822fc9d97ae0431f9c8759 (latest commit in branch) is the correct commit and has the modifications suggested

i should've sent my comment before pushing it, sorry

**Pull request merged**
