### PR TITLE
P2P + EU to RF Quest Improvements

### PR DESCRIPTION
**Pull request by Doniazade**
The purpose of this PR is:

1: Clarify to the player that EU automatically converts to RF. The current quest book implies it doesn't in the quest LV Power, but EU->RF autoconversion is enabled in gregtech.cfg. This is relevant to all players but especially in hard mode to not need converters for all the EU power you use.

2: Clarify how power P2P works. It has gotten more popular and we often see questions on Discord about this, hopefully this will cut down on them somewhat. The thing about the energy cells for tax+energy cells is especially common, which is why I put that in all red.

The world acceleration note is somewhat esoteric but used pretty often with world acc source and solar, and I want the player to be able to find those power options on their own without being misled into thinking that the signed intmax input limit is absolute.

The limit on EU P2P is signed long int (~9e18) for both amps and volts which is infinity for practical purposes, there is nothing that can receive and use more than this, not even dracoball. So all the player needs to know is there is no limit.

The P2P quest is also pretty wordy at this point and I would suggest making a separate power P2P quest, but I'm not experienced with BQ and I'd prefer it if someone else made it so it's all done right.

See below for screenshots with edited sections marked for convenience. Tested on 1.7.6 nightly

image

image

### CODE REVIEW

**Review by v3ect0rgames — COMMENTED** [review]
I'm pretty sure there are 4 Quest Book files. Make sure to change it in all of them. If this doesn't apply to expert mode, then still add it to the other default quests. I'm not 100% sure you need too

**Comment by Doniazade** [comment]
> I'm pretty sure there are 4 Quest Book files. Make sure to change it in all of them. If this doesn't apply to expert mode, then still add it to the other default quests. I'm not 100% sure you need to

Thanks, I'll get that in after work tomorrow + minor change to the cable quest.

**Review by v3ect0rgames — DISMISSED** [review]
Ok, just add to all 2/4, and it should be good to merge.

**Comment by v3ect0rgames** [comment]
also please do not use the main branch for prs, next time make a new branch

**Comment by v3ect0rgames** [comment]
by that i mean make a new branch on your fork, still merge to nomi-ceu main

**Comment by IntegerLimit** [comment]
> by that i mean make a new branch on your fork, still merge to nomi-ceu main

Its fine for a one-off PR.

**Comment by IntegerLimit** [comment]
> > I'm pretty sure there are 4 Quest Book files. Make sure to change it in all of them. If this doesn't apply to expert mode, then still add it to the other default quests. I'm not 100% sure you need to
> 
> Thanks, I'll get that in after work tomorrow + minor change to the cable quest.

It can be automated, but you have to also checkout Nomi-CEu/main as another branch name:
Simply go the the `tools` folder in your clone.
Do `npm install` (You may need to install npm)
Run `npm run gulp portQBChanges` and input the branch that you checked out Nomi-CEu/main as

Since this is a little complicated, I'll do this for this PR, but you can do this in the future.

**Review by IntegerLimit — APPROVED** [review]

**Comment by IntegerLimit** [comment]
Thank you for the PR!

**Comment by Doniazade** [comment]
> Thank you for the PR!
Glad to be able to contribute!

**Pull request merged**
