### PR TITLE
Miscellaneous Quest Book Fixes and Improvements

### PR DESCRIPTION
**Pull request by IntegerLimit**
This PR makes many changes to the Quest Book, reflecting new changes, fixing bugs, and improving accuracy and clarity.

Changes in *italics* are relevant to the nightly stage only, not to 1.7.3.

## Notes for Reviewers
- Genesis Prerequisites are not fully correct, but they are what they are for visuals. Also, the change in progression from Iron Supply to Basic Tools is miniscule.
- In HM, the Night Vision Quest is not connected to Simple RF Production as that causes issues with the quest not appearing when it is supposed to.

### Misc
- Rearranges Genesis Chapter
- Slight Rearrangement of Mid Game Chapter
- Streamlines Instruction Locations for Multi Building
- Sorts Required Items for EBF and Pyrolyse Oven Quests
- General Clarity and Coloring Improvements
- Mentions Sun's Black Hole Background in Warp Core Quest
- Updates Advanced Memory Card Quest With Changes in Labs 0.12.0
- Flux Capacitor Quest No Longer Requires Battery Buffer

### Additions
- Adds Quest for Excitation Coil Night Vision
- Adds Quest for Earlygame Fluid Storage and Collection
- Adds Quest for Simple Automation of Machines Pre-AE2
- Adds Mention of Black Hole Background in the Sun for Warp Core
- Adds Quest for AE2 Cutting Knives
- Adds Quest for Wireless Charging

### Improvements
- Improves Dependency Chains in Genesis
- Improves Interdimensional Networking Quest, adding more Debug and Setup Steps
- Improves Research Related Dependency Chains

### Fixes
- Fixes Issues with Polyethylene Boost Recommendation
- Fixes Dependencies of Magnesium End Game Quest
- Fixes Naquadah Reactor Quest Requesting Energy Hatch instead of Dynamo Hatch

### Removals
- Removes of LBB Task in Steam Dynamo Quest (Unsuitable Timing)
- Removes Steel Quest in Genesis
- Removes Hot Titanium Quest, Moves Automation Info to Vacuum Freezer
- *Removes of Conduit Probe + Capacitor Task in Uber Conduit Quest*

### Misc
- Mentions LV Compressor Usage in Making Rubber Sheets
- Moved Battery Buffer to The Beginning, after Electric Blast Furnace
  - When it is helpful, due to EBF's Large Power Draw

### Misc
- Reworks Genesis Chapter
  - Allows Completion with EU Power Generation or RF Power Generation
- Allows MV Converter Quest to Accept Converter or Transformer
- Separates Ethylene and Polyethylene into Two Quests (from NM)
- Recommends Arc Furnace (for Wrought Iron and Glass)
- States Differences Between Steam, High Pressure, and LV Machines
- Allows Staff of Travelling Quest to take Staff of Travelling or Dark Steel Travel Upgrade (from NM)

### Additions
- Adds Quest for Turbine Conversion Augment
- Adds Quest for Rock Breakers (Steam -> MV)
- Adds Quest for Large Bronze Boiler
- Adds Quest for Stone Processing
- Adds Quest for NuclearCraft Infinite Cobblestone Generator
- Adds Quest for Black Granite Processing (from NM)
- Adds Quest for Multi Fluid Hatches (from NM)
- Adds Quest for HV Rock Breaker (from NM)
- Adds Quest for Singleblock Miners (from NM)
- Adds Quest for Rubber (From Chemical Reactor and Fluid Solidifier)

### Improvements
- Improves Clarity of Steam Production Quest
- Improves Dependency Chains in Plastic-Related Quests

### Fixes
- Fixes Wrong Recommendation of Oil for Ethylene Production
- Fixes Wrong Block Requested for Naquadah Reactor Quest

### Removals
- Removes Light Fuel, Heavy Fuel and Patriot's Plastic Quests (from NM)
- Removes LV Compressor Quest

### CODE REVIEW

**Review by Doniazade — APPROVED** [review]
There is so much exciting stuff in this PR!

I don't have access to a client right now, so this review is based on the changelog and some code review.

>Misc
>    Rearranges Genesis Chapter
>    Slight Rearrangement of Mid Game Chapter
>    Streamlines Instruction Locations for Multi Building
>    Sorts Required Items for EBF and Pyrolyse Oven Quests
>    General Clarity and Coloring Improvements
These I will evaluate in-game, but they are clearly much needed polish.


>Additions
>    Adds Quest for Excitation Coil Night Vision
Very needed! This lets the player mine efficiently without using maximum brightness, so that the game looks better. 

>    Adds Quest for Earlygame Fluid Storage and Collection
Fluid storage has been recently reworked, so clearly this needs to be documented.

>    Adds Quest for Simple Automation of Machines Pre-AE2
I think this is greatly needed to make pre-AE2 feel more like meaningful content and less like hazing to make the player appreciate AE2 better.

>Improvements
>    Improves Dependency Chains in Genesis
Will evaluate in-game.

>Fixes
>    Fixes Issues with Polyethylene Boost Recommendation
Not discouraging TiCl4 is great, since it means the player is encouraged to actually use it. This adds a small automation (level emitting) challenge when it comes to stocking TiCl4 for boosting while still converting the rest to titanium metal.

>    Fixes Dependencies of Magnesium End Game Quest
This was maybe me when I redid those dependencies, oops.

>Removals
>    Removes of LBB Task in Steam Dynamo Quest (Unsuitable Timing)
I agree, LBB is early LV not late steam.

>    Removes Steel Quest in Genesis
I assume this is because it's part of the PBF quest instead.

>    Removes Hot Titanium Quest, Moves Automation Info to Vacuum Freezer
Great removal of superfluous quest. It's not even the first hot ingot.

>    Removes of Conduit Probe + Capacitor Task in Uber Conduit Quest
No comment here since I think this quest was added after I last played.

>Hard Mode
>Misc
>    Reworks Genesis Chapter
>        Allows Completion with EU Power Generation or RF Power Generation
Great change to properly support EU power only route (my favorite route because Greg power is more immersive to me personally)

>    Separates Ethylene and Polyethylene into Two Quests (from NM)
Very much needed, ethylene is used for much more than just PE, like acetone/acetic acid. Deserves the attention.

>    Recommend Arc Furnace (for Wrought Iron and Glass)
Correct.

>Additions
>    Adds Quest for Turbine Conversion Augment
Needed since this is the RF power meta pre petro power.

>    Adds Quest for Rock Breakers (Steam -> MV)
Very much needed and in my opinion NC cobble gens could be removed, if greg rock breakers are made fast enough for taranium line.

>    Adds Quest for Large Bronze Boiler
Extremely needed for HM power meta since power without LBB is quite painful before petro power.

>    Adds Quest for Stone Processing
Needed and good.

>    Adds Quest for NuclearCraft Infinite Cobblestone Generator
See comment for rock breaker, I'm fine keeping them or not, it's a design decision.

>    Adds Quest for Black Granite Processing (from NM)
Very much needed to make fluorine requirements reasonable, not easy to find without metagame knowledge.

>    Adds Quest for Multi Fluid Hatches (from NM)
Needed.

>    Adds Quest for HV Rock Breaker (from NM)
Also needed, since HV rock breaker introduces some useful processing besides just SiO2 line.

>    Adds Quest for Singleblock Miners (from NM)
I never found them very useful, but I haven't really used them that much either (besides in GTNH) so I can't comment on this really.

>Improvements
>    Improves Clarity of Steam Production Quest
>    Improves Dependency Chains in Plastic-Related Quests
Polish good.

>Fixes
>    Fixes Wrong Recommendation of Oil for Ethylene Production
Adjusting to the new petro meta is about time.

>Removals
>    Removes Light Fuel, Heavy Fuel and Patriot's Plastic Quests (from NM)
Needed cleanup, petro doesn't need a quest for every fraction.

**Comment by IntegerLimit** [comment]
PR awaiting secondary approval (with in-game testing) from Doni.

**Review by v3ect0rgames — APPROVED** [review]
All code changes look good for the commits after doni's approval

**Review by Doniazade — APPROVED** [review]
Reviewed based on in-game hard mode quest book.

I've realized that I can't possibly review the entirety of this thing without playing through the pack again. The changes Integer has made are clearly very well thought-through and the formatting of the new quests is pleasant.

In Genesis, this area can be broken into two pieces, putting the cable dependencies to the left and the rest to the right. There is plenty of room on the left side.

image

This piece separated from the rest to make it clearer that they are not associated:
image

This long cluster can be straightened and the pyrolyse shifted to also make it clearer that there is no connection. (I don't even like the pyrolyse myself because it just feels like a failed blast furnace)

I also think that there are probably too many side quests in this chapter and maybe they could be scaled down a bit.
image

I'm glad to see naq reactors got some attention, this is a good step towards an endgame with no source/emitter a mainstream difficulty option.

Making ethylene its own entry is good for clarity, since it makes the player aware that ethylene is in fact useful for other things like (especially) acetone via acetic acid.

Removing hot titanium was also a good choice I think, just like the earlier removal of the double plate quests.

I'm most excited about Mid Game not having any crossings anymore, it really feels like a new tab. I'm glad that something came out of the topological sketch that I made.

I'm approving this for player testing, I'm sure issues will come up but I think they can be hammered out as we go. Happy holidays.

**Comment by IntegerLimit** [comment]
> In Genesis, this area can be broken into two pieces, putting the cable dependencies to the left and the rest to the right. There is plenty of room on the left side.

I've tried my best in the latest commit, but most of those (apart from the storage crate) are already cable dependencies, so the impact is small. Here is the new layout:

image

**Comment by IntegerLimit** [comment]
> This piece separated from the rest to make it clearer that they are not associated:

They are actually related, its just not directly connected for visuals' sake.

**Comment by IntegerLimit** [comment]
Remaining Planned Changes:

- Add Quest for Wireless RF Charging
- Improve Quests for Flux Capacitor and Battery Buffer (LV)
- Update Quests for Better P2P Changes
  - Hover Info per Device
  - Filtering (Especially Distance)
  - Sorting
  - Use of Renaming P2Ps

**Comment by Doniazade** [comment]
Reviewed based on comments.

> > In Genesis, this area can be broken into two pieces, putting the cable dependencies to the left and the rest to the right. There is plenty of room on the left side.
> 
> I've tried my best in the latest commit, but most of those (apart from the storage crate) are already cable dependencies, so the impact is small. Here is the new layout:
> 
> image

This is what I imagined, roughly. I think it's good and it makes the page look a bit more balanced.

> > This piece separated from the rest to make it clearer that they are not associated:
> 
> They are actually related, its just not directly connected for visuals' sake.

Fair, no change needed. It's mainly that there's no spacing in the big block of quests, so it gets a little dense visually. 

> Remaining Planned Changes:
> 
>     * [x]  Add Quest for Wireless RF Charging
> 
>     * [x]  Improve Quests for Flux Capacitor and Battery Buffer (LV)
> 
>     * [x]  Update Quests for Better P2P Changes
>       
>       * Hover Info per Device
>       * Filtering (Especially Distance)
>       * Sorting
>       * Use of Renaming P2Ps

Information about charging is absolutely an important priority, the Parabolic Flux Coupling quest is not obvious enough so I'm glad this important charging QoL is being highlit better.

Similarly P2P improvements are also very much needed, given how important they have become compared to earlier versions of the game.

All good with me, and happy new year!

**Comment by IntegerLimit** [comment]
Thank you, and happy new year to you too!

**Pull request merged**
